version: '3.4'

services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_test
    ports:
      - "13306:3306"

  user_db:
    build: ./mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_user_test
    ports:
      - "13307:3306"

  app:
    build: .
    environment:
      DB_NAME: govwifi_test
      DB_PASS: root
      DB_USER: root
      DB_HOSTNAME: db
      USER_DB_NAME: govwifi_user_test
      USER_DB_PASS: root
      USER_DB_USER: root
      USER_DB_HOSTNAME: user_db
      RACK_ENV: development
      AUTHORISED_EMAIL_DOMAINS_REGEX: "\\.gov\\.uk$$"
