version: '3.4'

services:
  db:
    platform: linux/x86_64
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_test
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10

  app:
    platform: linux/x86_64
    build: .
    environment:
      DB_NAME: govwifi_test
      DB_PASS: root
      DB_USER: root
      DB_HOSTNAME: db
      RACK_ENV: development
      S3_SIGNUP_ALLOWLIST_OBJECT_KEY: 'somefile'
      S3_SIGNUP_ALLOWLIST_BUCKET: 'somebucket'
      NOTIFY_API_KEY: dummy_key-00000000-0000-0000-0000-000000000000-00000000-0000-0000-0000-000000000000
      GOVNOTIFY_BEARER_TOKEN: 'dummy-bearer-token-1234'
      NOTIFY_DO_NOT_REPLY: 'do_not_reply_email_template_id'
      NOTIFY_SUPPORT_REPLY: 'support_reply_email_template_id'
    expose:
        - "8080"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      db:
        condition: service_healthy
