version: '3.4'

services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_test
    expose:
      - "3306"

  app:
    build: .
    environment:
      DB_NAME: govwifi_test
      DB_PASS: root
      DB_USER: root
      DB_HOSTNAME: db
      RACK_ENV: development
      S3_SIGNUP_WHITELIST_OBJECT_KEY: 'somefile'
      S3_SIGNUP_WHITELIST_BUCKET: 'somebucket'
      NOTIFY_API_KEY: dummy_key-00000000-0000-0000-0000-000000000000-00000000-0000-0000-0000-000000000000
      FIRETEXT_TOKEN: 'dummy-token-1234'
      GOVNOTIFY_BEARER_TOKEN: 'dummy-bearer-token-1234'
    expose:
        - "8080"
    depends_on:
      - db
