version: '3.4'

services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: govwifi_test
    expose:
      - "3306"

  app:
    build: .
    environment:
      DB_NAME: govwifi_test
      DB_PASS: root
      DB_USER: root
      DB_HOSTNAME: db
      RACK_ENV: development
      S3_SIGNUP_WHITELIST_OBJECT_KEY: 'somefile'
      S3_SIGNUP_WHITELIST_BUCKET: 'somebucket'
    expose:
        - "8080"
    depends_on:
      - db
