---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "((readonly_private_ecr_repo_url))"
    tag: concourse-builder-latest

# https://github.com/concourse/builder-task#params
params:
  REPOSITORY: 'govwifi/user-signup-api'
  CONTEXT: src
  BUILD_ARG_BUNDLE_INSTALL_CMD: 'bundle install --without test'
  TAG:

inputs:
  - name: src
  - name: wordlist-file

outputs:
  - name: image

caches:
  - path: cache

run:
  path: sh
  args:
    - '-exc'
    - |
      cp wordlist-file/wordlist-short ./src/tmp/wordlist
      echo "$TAG" > image/tag
      build
