---
platform: linux

params:
  STAGE:
  AWS_ACCESS_KEY_ID:
  AWS_DEFAULT_REGION:
  AWS_SECRET_ACCESS_KEY:

  # These are set for deploy.sh and migrate.sh
  SERVICE_NAME: "user-signup-api-service"
  CLUSTER_NAME: "api-cluster"
  TASK_NAME: "user-signup-api"
  CONTAINER_NAME: "user-signup-api"

inputs:
  - name: src
  - name: deploy-tools

run:
  path: bash
  args:
    - '-exc'
    - |
      src/ci/tasks/scripts/migrate.sh
      src/ci/tasks/scripts/deploy.sh
