---
platform: linux

inputs:
  - name: src
  - name: docker-cache/app-prebuilt
  - name: docker-cache/mysql-image
  - name: docker-cache/ruby-image

params:
  ON_CONCOURSE: true

run:
  path: docker-wrapper
  args: [src/ci/tasks/scripts/lint.sh]
