notify_sms_template_ids:
  credentials: sms_credentials_template_id
  help_menu: sms_help_menu_template_id
  recap: sms_recap_template_id
  device_help:
    android: sms_device_help_android_template_id
    blackberry: sms_device_help_blackberry_template_id
    mac: sms_device_help_mac_template_id
    iphone: sms_device_help_iphone_template_id
    windows: sms_device_help_windows_template_id
  active_users_signup_survey: active-users-mobile-signup-survey-template
  followup: sms_followup_template_id
  credentials_expiring_notification: 3d24dcb3-503c-4045-9ac4-22d0868eb49f
  notify_user_account_removed_sms: 4976e93a-e9e8-4e64-bdd0-5aeaf188c56b

notify_email_template_ids:
  self_signup_credentials: email_self_signup_credentials_template_id
  sponsor_rejection: 17119b7d-d72c-49db-b770-20f4c25c379f
  rejected_email_address: email_rejected_email_address_template_id
  sponsored_credentials: email_sponsored_credentials_template_id
  sponsor_confirmation:
    plural: email_sponsor_confirmation_plural_template_id
    singular: email_sponsor_confirmation_singular_template_id
    failed: email_sponsor_confirmation_failed_template_id
  active_users_signup_survey: active-users-email-signup-survey-template
  followup: email_followup_template_id
  credentials_expiring_notification: 30af3d4a-6bc0-4455-93b6-9c0422e5109d
  notify_user_account_removed: 6b0234d7-ede5-4593-bd10-fee9269fa656

do_not_reply_email_id: do_not_reply_email_template_id
