name: Upgrade Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 15 * 0" # Runs monthly (in the middle to avoid any date clashes)

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade-ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: run updater
        uses: govwifi/shared-actions-workflows/.github/actions/ruby-updater@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          main-branch: master